"""
Evdence analysis agent.
"""

from src.services.qwen_service import ask_qwen


class EvidenceAnalyzer:
    """
    Analyze security evidence and produce findings.
    """

    def analyze(self, evidence: str) -> str:
        """
        Analyze raw security evidence.

        Args:
            evidence: Raw security event.

        Returns:
            Analysis generated by Qwen.
        """

        prompt = f"""
You are a senior SOC analyst.

Analyze the following security evidence.

Evidence:
{evidence}

Provide:

1. Threat Summary
2. Risk Level
3. Attack Classification
4. Recommended Actions
"""

        return ask_qwen(prompt)
